Repository jazzband/sorl-thumbnail, pull requests merged in 2019-01, with the labels that each got.

#574 Update examples.rst
  docs/examples.rst
Labels: almost-ready, simple-fix

#576 Add badges
  README.rst
Labels: almost-ready, critical, needs-review, simple-fix

#548 fixing typo, and add Cropbox feature in Wand/Convert Engine
  README.rst
  docs/template.rst
  sorl/thumbnail/engines/convert_engine.py
  sorl/thumbnail/engines/wand_engine.py
  tests/thumbnail_tests/test_engines.py
Labels: needs-review

#577 Remove deprecated option
  .travis.yml
Labels: compatibility, needs-review, simple-fix
